name: 'Deploy to AWS EC2 Sevice'

on:
  push:
    branches:
      - main

jobs:
  gitaction-ec2-deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Repoitory Checkout code, 소스 가져오기 
          uses: actions/checkout@v4

        # EC2에 접속하기 위해 pem파일을 깃허브 내 리눅스에 생성
        - name: Create SSH key file - pem 파일 생성
          run: |
            echo "${{secrets.EC2_KEY}}" | base64 --decode > ./wj-key.pem
            chmod 600 ./wj-key.pem
            ls -al
        
        # -o: 경고창 없이 바로 진입
        # -r: 디렉토리 전체 복사
        - name: Deploy to EC2 instance - ec2 서버로 배포
          run: |
            scp -o StrictHostKeyChecking=no -i ./wj-key.pem -r . ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}}:~/app

        - name: EC2 환경 세팅 및 구동
          run: |
            ssh -i app/wj-key.pem -o StrictHostKeyChecking=no ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}} << 'E0F'
            cd ~/app
            sudo apt update && sudo apt upgrade -y
            sudo apt install python3-pip python3-venv -y
            E0F